[
  {":0:unknown_function Function IEx.dont_display_result/0 does not exist.", :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Atom.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.BitString.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Float.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Function.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Integer.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.List.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Map.__impl__/1 does not exist.", :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.PID.__impl__/1 does not exist.", :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Port.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Reference.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Encode.Tuple.__impl__/1 does not exist.",
   :unknown_function},
   {":0:unknown_function Function Creep.Packet.Decode.Atom.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.BitString.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.Float.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.Function.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.Integer.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.List.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.Map.__impl__/1 does not exist.", :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.PID.__impl__/1 does not exist.", :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.Port.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.Reference.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Creep.Packet.Decode.Tuple.__impl__/1 does not exist.",
   :unknown_function}
]